# Generated by Django 4.2 on 2023-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('types', models.CharField(max_length=255, null=True)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonFile',
            fields=[
                ('name', models.CharField(help_text='Pokemons to load', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
