# Generated by Django 4.2 on 2023-05-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pokemon_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon1', to='pokedex.pokemon')),
                ('pokemon_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon2', to='pokedex.pokemon')),
                ('pokemon_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon3', to='pokedex.pokemon')),
                ('pokemon_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon4', to='pokedex.pokemon')),
                ('pokemon_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon5', to='pokedex.pokemon')),
                ('pokemon_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon6', to='pokedex.pokemon')),
            ],
        ),
    ]
