# Generated by Django 4.2 on 2023-05-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_team_delete_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pokemon_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon2', to='pokedex.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pokemon_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon3', to='pokedex.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pokemon_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon4', to='pokedex.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pokemon_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon5', to='pokedex.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pokemon_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon6', to='pokedex.pokemon'),
        ),
    ]
